In [143]:
# Verificando versão do python
!python --version

Python 3.8.8


In [144]:
# Importando bibliotca numpy
import numpy as np

In [145]:
km = np.loadtxt('carros-km.txt')

In [146]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [147]:
# Importando dataset carro-anos e informando que o tipo será inteiro
anos = np.loadtxt('carros-anos.txt', dtype = int)
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

# Quilometragem media por ano

In [148]:
km_Media = km / (2019 - anos)

<ipython-input-148-bde2acec3580>:1: RuntimeWarning: invalid value encountered in true_divide
  km_Media = km / (2019 - anos)


In [149]:
km_Media


array([2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
       1.98130769e+03, 1.53257143e+03,            nan, 7.75990000e+03,
       1.10218889e+04, 4.74725000e+03, 7.56411765e+02, 6.71000000e+02,
       4.98738889e+03,            nan, 4.14570000e+03, 3.85356667e+04,
       6.63557143e+03,            nan, 1.23620000e+04, 7.58650000e+03,
       5.95252941e+03,            nan, 3.92316000e+03, 3.67710714e+03,
                  nan,            nan, 1.93166667e+03,            nan,
       3.46164706e+03, 3.37075000e+03, 1.37104545e+03, 2.22216667e+03,
       1.77200000e+04, 1.20742857e+03, 1.81368000e+04, 1.83229167e+03,
                  nan,            nan, 5.52600000e+02,            nan,
       1.55691667e+04, 2.54762500e+03,            nan, 5.07658824e+03,
                  nan, 5.73823529e+02, 4.66300000e+03, 1.33055556e+02,
                  nan, 5.02181250e+03, 8.55540000e+03, 3.88430769e+03,
       3.56400000e+03, 7.22669231e+03, 3.92722222e+03, 3.24028000e+03,
      

In [150]:
type(km_Media)

numpy.ndarray

# operação matematicas

**Adição**

In [151]:
5 + 5

10

**Subtração**


In [152]:
5 - 5

0

**Multiplicação**

In [153]:
 5 * 5

25

**Divisao**

In [154]:
18 / 5

3.6

In [155]:
18 // 5

3

**Exponenciação**

In [156]:
 5 ** 3

125

In [157]:
10 % 5

0

In [158]:
10 % 3

1

**Expressão matemáticas**

In [159]:
 5 * 2 + 5 *3

25

In [160]:
(5 * 2) + (5 *3)

25

In [161]:
5 * (2 + 5) * 3 

105

# Variavel

O ultimo resultado impresso, é atribuido na variavel _

In [162]:
5 * 2

10

In [163]:
_ + 3 * 2 

16

In [164]:
_ / 2

8.0

# Varivéis

atribuições

In [165]:
ano_atual = 2017
ano_fabricacao = 2005
km_total = 44410.0

print(ano_atual, ano_fabricacao, km_total)

2017 2005 44410.0


In [166]:
# Realizando operações com as variaveis

km_media = km_total / (ano_atual - ano_fabricacao)
km_media

3700.8333333333335

In [167]:
# Analisando com outros dados

ano_atual = 2017
ano_fabricacao = 2005
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

3700.8333333333335

In [168]:
# Preditando a quilometragem no ano seguinte

ano_atual = 2017
ano_fabricacao = 2005
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_total = km_total + km_media
km_total

48110.833333333336

In [169]:
ano_atual = 2017
ano_fabricacao = 2005
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_total  += km_media
km_total

48110.833333333336

# Declaração Multipla

In [170]:
ano_atual, ano_fabricacao, km_total = 2017, 2005, 44410.0
print(ano_atual, ano_fabricacao, km_total)

2017 2005 44410.0


In [171]:
ano_atual, ano_fabricacao, km_total = 2017, 2005, 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

3700.8333333333335

# Tipos de variaveis

**NUMEROS**

In [172]:
ano_atual = 2019

In [173]:
type(ano_atual)

int

In [174]:
km_total = 44400.0

In [175]:
type(km_total)

float

**BOOLEANOS**

In [176]:
zero_km = True

In [177]:
type(zero_km)

bool

In [178]:
zero_km = False

In [179]:
type(zero_km)

bool

**STRINGS**

In [180]:
nome = "Jetta Variant"
nome

'Jetta Variant'

In [181]:
nome = "Jetta 'Variant'"
nome

"Jetta 'Variant'"

In [182]:
carro = '''
        nome
        idade
        nota
    '''

In [183]:
carro

'\n        nome\n        idade\n        nota\n    '

In [184]:
type(carro)

str

**NONE**

In [185]:
quilometragem = None
quilometragem

In [186]:
type(quilometragem)

NoneType

# Conversão de dados

In [187]:
a = 10
b = 20
c = 'Python é '
d = 'legal'

In [188]:
type(a)

int

In [189]:
type(b)

int

In [190]:
type(c)

str

In [191]:
type(d)

str

In [192]:
a + b

30

In [193]:
c + d

'Python é legal'

**CONVERSÕES**

In [194]:
# transformando em string
str(a)

'10'

In [195]:
c + str(a)

'Python é 10'

In [196]:
# transformando em float
float(a)

10.0

In [197]:
var = 3.1414

In [198]:
# transformando em inteiro
int(var)

3

In [199]:
var = 3.99

In [200]:
int(var)

3

#  Identação, comentarios  e formatação de strings

Identação

In [201]:
# Definindo variaveis
ano_atual = 2019
ano_fabricacao = 2019
    
if (ano_atual == ano_fabricacao):  # testando se a condição é verdadeira
    print('Verdadeiro')
else:                    # se não, é false
    print('Falso')

Verdadeiro


## Coméntarios é sempre bom usar, para explicar o que cada linha de codigo esta fazendo

**Formatação**

In [202]:
print("Olá, {}!".format('Leonardo'))

Olá, Leonardo!


In [203]:
print('Olá, {}! Esse é seu acesso de número {}'.format('Leonardo', 32))

Olá, Leonardo! Esse é seu acesso de número 32


In [204]:
print('Olá, {nome}! Esse é seu acesso de número {acessos}'.format(nome = 'Leonardo', acessos = 32))

Olá, Leonardo! Esse é seu acesso de número 32


**F-strings**

In [205]:
nome = 'Leonardo'
acessos = 32

In [206]:
print(f'Olá, {nome}! Esse é seu acesso de número {acessos}')

Olá, Leonardo! Esse é seu acesso de número 32


# Usando listas

Lista sao sequencias mutaveis, que sao utilizadas para armazenar coleção de itens

Listas são estruturas de dados que representam um tipo de mapeamento

In [207]:
# Criando lista de acesserios de carros
acessorios = ['Rodas de liga', 'Trava elétricas', 'Piloto Automatico', 'Bancos de couro', 'Ar concicionado',
              'Sensor de estacioanmento', 'Sensor crespusculo', 'Sensor de chuva']
acessorios

['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado',
 'Sensor de estacioanmento',
 'Sensor crespusculo',
 'Sensor de chuva']

In [208]:
type(acessorios)

list

In [209]:
# Criando duas listas, carro 1 e carro 2 com todos os acessorios e informações de cada carro
carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, 
           ['Rodas de liga', 'Trava elétricas','Piloto automático', 88078.64]]
carro_2 = ['Passat', 'Motor diesel', 1991, 5712.0, False, 
           ['Central Multimídia', 'Teto panorâmico','Freio ABS', 106161.94]]

In [210]:
# Criando varivel carro, recebendo o valor das listas do carros e rodando
carros = [carro_1, carro_2]
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Trava elétricas', 'Piloto automático', 88078.64]],
 ['Passat',
  'Motor diesel',
  1991,
  5712.0,
  False,
  ['Central Multimídia', 'Teto panorâmico', 'Freio ABS', 106161.94]]]

# Operações com Lista

**x in A**

In [211]:
acessorios

['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado',
 'Sensor de estacioanmento',
 'Sensor crespusculo',
 'Sensor de chuva']

In [212]:
'Rodas de liga' in acessorios

True

In [213]:
'4 x 4 'in acessorios

False

**A + B**

In [214]:
A = ['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro']

B = ['Ar concicionado',
 'Sensor de estacioanmento',
 'Sensor crespusculo',
 'Sensor de chuva']

In [215]:
A + B

['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado',
 'Sensor de estacioanmento',
 'Sensor crespusculo',
 'Sensor de chuva']

**Len(A)**

tamanho da lista

In [216]:
len(acessorios)

8

# Seleção de Lista

In [217]:
acessorios

['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado',
 'Sensor de estacioanmento',
 'Sensor crespusculo',
 'Sensor de chuva']

In [218]:
# Acessando indice da lista
acessorios[0]

'Rodas de liga'

In [219]:
acessorios[1]

'Trava elétricas'

In [220]:
acessorios[2]

'Piloto Automatico'

In [221]:
acessorios[-1]

'Sensor de chuva'

In [222]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Trava elétricas', 'Piloto automático', 88078.64]],
 ['Passat',
  'Motor diesel',
  1991,
  5712.0,
  False,
  ['Central Multimídia', 'Teto panorâmico', 'Freio ABS', 106161.94]]]

In [223]:
carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Trava elétricas', 'Piloto automático', 88078.64]]

In [224]:
# Acessando o primeiro indice da primeira lista 
carros[0][0]

'Jetta Variant'

In [225]:
carros[0][-1]

['Rodas de liga', 'Trava elétricas', 'Piloto automático', 88078.64]

In [226]:
carros[0][-1][1]

'Trava elétricas'

 # **Fatiamentos  slicing**

**A[ i : j ]**

Ulitmo é exlusivo nao entra na lista

In [227]:
acessorios

['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado',
 'Sensor de estacioanmento',
 'Sensor crespusculo',
 'Sensor de chuva']

In [228]:
acessorios[3:5]

['Bancos de couro', 'Ar concicionado']

In [229]:
acessorios[0:5]

['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado']

In [230]:
acessorios[2:]

['Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado',
 'Sensor de estacioanmento',
 'Sensor crespusculo',
 'Sensor de chuva']

In [231]:
acessorios[:5]

['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado']

# Metódos de lista


**A.sort()**

ordena a lista a


In [232]:
acessorios

['Rodas de liga',
 'Trava elétricas',
 'Piloto Automatico',
 'Bancos de couro',
 'Ar concicionado',
 'Sensor de estacioanmento',
 'Sensor crespusculo',
 'Sensor de chuva']

In [233]:
acessorios.sort()
acessorios

['Ar concicionado',
 'Bancos de couro',
 'Piloto Automatico',
 'Rodas de liga',
 'Sensor crespusculo',
 'Sensor de chuva',
 'Sensor de estacioanmento',
 'Trava elétricas']

**A.append()**

adiciona elemento X no final da lista A

In [234]:
acessorios.append('4 x 4')
acessorios

['Ar concicionado',
 'Bancos de couro',
 'Piloto Automatico',
 'Rodas de liga',
 'Sensor crespusculo',
 'Sensor de chuva',
 'Sensor de estacioanmento',
 'Trava elétricas',
 '4 x 4']

**A.pop()**

remove um elemento da lista. 

Por default ele sempre remove o ultimo elemento da lista, nesse caso deve-se inidicar qual elemento 


In [235]:
acessorios.pop()

'4 x 4'

In [236]:
acessorios

['Ar concicionado',
 'Bancos de couro',
 'Piloto Automatico',
 'Rodas de liga',
 'Sensor crespusculo',
 'Sensor de chuva',
 'Sensor de estacioanmento',
 'Trava elétricas']

In [237]:
# apagando rodas de liga
acessorios.pop(3)
acessorios

['Ar concicionado',
 'Bancos de couro',
 'Piloto Automatico',
 'Sensor crespusculo',
 'Sensor de chuva',
 'Sensor de estacioanmento',
 'Trava elétricas']

**A.copy()**

cria uma copia da lista A

In [238]:
acessorios_2 = acessorios.copy()
acessorios_2

['Ar concicionado',
 'Bancos de couro',
 'Piloto Automatico',
 'Sensor crespusculo',
 'Sensor de chuva',
 'Sensor de estacioanmento',
 'Trava elétricas']

In [239]:
# Apos criado a copia da lista acessorios, estou adicionando a copia elemento 4 x 4 sem alterar a verdadeira lista
acessorios_2.append("4 x 4")
acessorios_2

['Ar concicionado',
 'Bancos de couro',
 'Piloto Automatico',
 'Sensor crespusculo',
 'Sensor de chuva',
 'Sensor de estacioanmento',
 'Trava elétricas',
 '4 x 4']

In [240]:
# a lista atual nao foi alterada
acessorios

['Ar concicionado',
 'Bancos de couro',
 'Piloto Automatico',
 'Sensor crespusculo',
 'Sensor de chuva',
 'Sensor de estacioanmento',
 'Trava elétricas']

# Estruturas de repetições e condicionais



**Instrução for**

**loops com for**

In [241]:
acessorios

['Ar concicionado',
 'Bancos de couro',
 'Piloto Automatico',
 'Sensor crespusculo',
 'Sensor de chuva',
 'Sensor de estacioanmento',
 'Trava elétricas']

In [242]:
for item in acessorios:
    print(item)

Ar concicionado
Bancos de couro
Piloto Automatico
Sensor crespusculo
Sensor de chuva
Sensor de estacioanmento
Trava elétricas


**List Comprehensions**

In [243]:
range(10)

range(0, 10)

In [244]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [245]:
for i in range(10):
    print(i **2)

0
1
4
9
16
25
36
49
64
81


In [246]:
# criando uma lista vazia, e fazendo um lopp for com valor ao quadrado, sendo adicionando 10 elementos no objeto quadrado
quadrado = []
for i in range(10):
    quadrado.append(i **2)
    
quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [247]:
# Outra forma de se fazer tambem, a diferença é que o resultado dessa lista nao é atribuido ao objeto quadrado
[i **2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

**Loops aninhados**

In [248]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [249]:
for lista in dados:
    print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [250]:
# Varrendo tudo
for lista in dados:
    for item in lista:
        print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [251]:
# Agora lista tem todas informações
acessorios = []

for lista in dados:
    for item in lista:
        acessorios.append(item)
acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

**Set**

remover duplicados

In [252]:
list(set(acessorios))

['Travas elétricas',
 'Sensor de estacionamento',
 'Bancos de couro',
 'Controle de estabilidade',
 'Ar condicionado',
 'Sensor de chuva',
 'Painel digital',
 'Piloto automático',
 'Câmbio automático',
 'Sensor crepuscular',
 'Teto panorâmico',
 'Vidros elétricos',
 '4 X 4',
 'Câmera de estacionamento',
 'Central multimídia',
 'Rodas de liga',
 'Freios ABS']


**List Comprehension**

In [253]:
[item for lista in dados for item in lista ]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [254]:
# Removendo duplicados
list(set([item for lista in dados for item in lista ]))

['Travas elétricas',
 'Sensor de estacionamento',
 'Bancos de couro',
 'Controle de estabilidade',
 'Ar condicionado',
 'Sensor de chuva',
 'Painel digital',
 'Piloto automático',
 'Câmbio automático',
 'Sensor crepuscular',
 'Teto panorâmico',
 'Vidros elétricos',
 '4 X 4',
 'Câmera de estacionamento',
 'Central multimídia',
 'Rodas de liga',
 'Freios ABS']

# Instrução If

if <condição>:

    <instruções caso a condição seja verdadeira>

In [272]:
# Criando lista dados
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
 ]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [273]:
for lista in dados:
    print(lista)

['Jetta Variant', 2003, False]
['Passat', 1991, False]
['Crossfox', 1990, False]
['DS5', 2019, True]
['Aston Martin DB4', 2006, False]
['Palio Weekend', 2012, False]
['A5', 2019, True]
['Série 3 Cabrio', 2009, False]
['Dodge Jorney', 2019, False]
['Carens', 2011, False]


In [274]:
# Listando somente os carros que sao 0km
zero_km_y = []
for lista in dados:
    if(lista[2] == True):
        zero_km_y.append(lista)
zero_km_y

[['DS5', 2019, True], ['A5', 2019, True]]

In [258]:
# Verificando os carros que nao sao 0km
zero_km_n = []
for lista in dados:
    if(lista[2] == False):
        zero_km_n.append(lista)
zero_km_n

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]


**List Comprehension**

In [275]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [276]:
A, B, C = [], [], []

for lista in dados:
    if(lista[1] <= 2000): # se na lista o ano for menos que 2000, entra na lista A
         A.append(lista)
    elif(lista[1] > 2000 and lista[1] <= 2010):  # se for maior que 2000 ano de fabricação e menor que 2010, entra na lista B
        B.append(lista)
    else:              
        C.append(lista)  # se nao, entra na lista C

In [277]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [279]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [280]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

**Observação quando tem for com duas listas**

In [261]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

In [262]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2

# Lembre-se que o operador de soma (+), quando aplicado em duas listas, retorna a concatenação destas listas.

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

**if-else**

if condição:
    instruções caso a condição seja verdadeira
    
else:
    instruções caso a condição não seja verdadeira

In [263]:
zero_km_y, zero_km_n = [], []

for lista in dados:
    if(lista[2] == True):
        zero_km_y.append(lista)
    else:
        zero_km_n.append(lista)

In [264]:
zero_km_y

[]

In [265]:
zero_km_n

[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]

In [266]:
dados

[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]

**if-elif-else**

if condição 1:
    instruções caso a condição 1 seja verdadeira
    
elif condição 2:
    instruções caso a condição 2 seja verdadeira
    
elif condição 3:
    instruções caso a condição 3 seja verdadeira
                        .
                        .
                        .
                        
else:
    instruções caso as condições anteriores não sejam verdadeiras

**AND E OR**

e  ou

&&  ||

In [267]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [268]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [269]:
# Criando condições baseado no Ano de fabricação
A, B, C = [], [], []

for lista in dados:
    if(lista[1] <= 2000): # se na lista o ano for menos que 2000, entra na lista A
         A.append(lista)
    elif(lista[1] > 2000 and lista[1] <= 2010):  # se for maior que 2000 ano de fabricação e menor que 2010, entra na lista B
        B.append(lista)
    else:              
        C.append(lista)  # se nao, entra na lista C

TypeError: '<=' not supported between instances of 'str' and 'int'

In [ ]:
A

In [ ]:
B

In [ ]:
C

# Numpy Básico

**Criando arrays numpy**

A partir de listas

In [281]:
km = np.array([1000, 2300, 1500, 4000])
km

array([1000, 2300, 1500, 4000])

In [282]:
# tipo
type(km)

numpy.ndarray

In [283]:
km.dtype

dtype('int32')

**A partir de dados externos**

In [284]:
#Carregando conjunto de dados carros km, e definindo a saida como inteiro
km = np.loadtxt(fname = "carros-km.txt", dtype = int)
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [285]:
km.dtype

dtype('int32')

**Arrays com duas dimensões**

In [286]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [287]:
acessorios = np.array(dados)
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [288]:
# Consultando tamanho a dimensao no caso
km.shape

(258,)

In [289]:
acessorios.shape

(3, 8)

**Comparando desempenho com listas**

In [290]:
np_array = np.arange(1000000)

In [291]:
py_list = list(range(1000000))

In [292]:
#Consigo ver o desepenho em tempo da linha do codigo
%time for _ in range(100): np_array *= 2

Wall time: 66.5 ms


In [293]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

Wall time: 10.4 s


Podemos concluir que, os arrays têm um desempenho muito melhor que o das listas quando fazemos operações matemáticas com eles.

# Operaçãoes aritmétricas com arrays numpy

In [294]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [295]:
# Vamos descobrir quantos anos tem o carro
 idade = 2019 - anos

IndentationError: unexpected indent (<ipython-input-295-e4f5fb4e8c6e>, line 2)

Não é possível fazer a subtração de um inteiro por uma lista. Entretanto, isso é possível com os arrays Numpy.

In [296]:
# Fazeno a operção da idade do com, porém com array numpy
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [297]:
idade = 2019 - anos
idade

array([16, 28, 29,  0, 13])

Diferença dos anos comparado a 2019

**Operações entre arrays**

In [298]:
km_media = km / idade
km_media

<ipython-input-298-c575ad6567e5>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = km / idade


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

Warning e devido o valor zero esta sendo divido

In [299]:
4000 / (2019 - 2003)

250.0

# Operações com arrays de duas dimensões

In [300]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [301]:
# Dimensao dos dados lxc
dados.shape

(2, 5)

In [302]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [303]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [304]:
km_media = dados[0] / (2019 - dados[1])
km_media

<ipython-input-304-dac51efab2ed>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = dados[0] / (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

Warning e devido o valor zero esta sendo divido

# Seleções com arrays numpy 

In [305]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

**Indexação**

Indexacão começa no zero

In [306]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [307]:
contador[0]

0

In [308]:
item  = 6
index = item  - 1
contador[index]

5

In [309]:
contador[-1]

9

In [310]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [311]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

Dica:

**ndarray[linha][coluna] ou ndarray[linha, coluna]**

In [312]:
dados[1][2]

1990.0

In [313]:
dados[1,2]

1990.0

# Fatiamentos

A sintaxe para realizar fatiamento em um array Numpy é i:j:k onde i é o índice inicial, j é o índice de parada, e k é o indicador de passo ( k≠0 )

In [314]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [315]:
# Quero trazer até o 3
contador[1:4]

array([1, 2, 3])

In [316]:
# Quero trazer até o 7 em dois passos
contador[1:8:2]

array([1, 3, 5, 7])

In [317]:
# Pegar os numeros pares
contador[::2]

array([0, 2, 4, 6, 8])

In [318]:
# Pegar os numeros impares
contador[1::2]

array([1, 3, 5, 7, 9])

In [319]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [320]:
dados[:, 1:3][1]

array([1991., 1990.])

In [321]:
dados[:, 1:3][0] / (2019 - dados[:, 1:3][1])

array([ 204.        , 1280.10344828])

In [322]:
dados[0] / (2019 - dados[1])

<ipython-input-322-fb26cb8e809a>:1: RuntimeWarning: invalid value encountered in true_divide
  dados[0] / (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# Indexacão com array booleano

In [323]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [324]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [325]:
contador[contador > 5]

array([6, 7, 8, 9])

In [326]:
contador[[False, False, False, False, False, False,  True,  True,  True,
        True]]

array([6, 7, 8, 9])

In [327]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [328]:
# Verificando se tem carros com ano depois de 2000
dados[1] > 2000

array([ True, False, False,  True,  True])

In [329]:
# Verificando quais carros tem o ano depois de 2000 nas duas linhas
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [330]:
# Verificando se tem carros com ano abaixo de 2000

dados[1] < 2000

array([False,  True,  True, False, False])

In [331]:
# Verificando quais carros tem o ano abixo de 2000 nas duas linhas
dados[:, dados[1] < 2000]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

# Atributos e metodos de arrays numpy


In [332]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

**Atributos**

**ndarray.shape**

Retorna uma tupla com as dimensões do array

In [333]:
dados.shape

(2, 5)

Mostra quantas linhas e colunas

**ndarray.ndim**

retorna o numero de dimensões do array

In [334]:
dados.ndim

2

**ndarray.size**

numero de elementos do array

In [335]:
dados.size

10

**ndarray.dtype**

retorna o tipo do array

In [336]:
dados.dtype

dtype('float64')

**ndarray.T**

Retorna um array transposto, isto é, converte linhas em colunas e vice versa

In [337]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [338]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

**ndarray.tolist()**

retorna um array com uma lista python

In [339]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

**ndarray.reshape(shape[, order])**

Retorna um array, com os mesmos dados, com uma nova forma

In [340]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [341]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [342]:
contador.reshape((5,2), order = 'c')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [343]:
# Fortran
contador.reshape((5,2), order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [344]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [345]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [346]:
np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [347]:
# transformando as informações de cada carro em cada linha
np.array(info_carros).reshape((5,2), order = 'F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

**ndarray.resize(new_shape[, refcheck])**

Altera a forma e o tamanho do array

In [348]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [349]:
# criando uma nova linha
dados_new.resize((3,5), refcheck =False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [350]:
# Adicionando dados a nova linha, no caso a média de quilometragem por ano
dados_new[2] = dados_new[0] / (2019 - dados[1])

<ipython-input-350-80eb3c53893c>:2: RuntimeWarning: invalid value encountered in true_divide
  dados_new[2] = dados_new[0] / (2019 - dados[1])


In [351]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

# Estatisticas com arrays Numpy

In [352]:
# Carregando tres dataset

km = np.loadtxt('carros-km.txt', dtype = int)
anos = np.loadtxt('carros-anos.txt')
valor = np.loadtxt('carros-valor.txt')

In [353]:
anos.shape

(258,)

In [354]:
# Criando dataset de duas dimensões e adicionando os tres dataset km,valor e ano. Cada um, em sua respectiva coluna
dataset = np.column_stack((anos,km,valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [355]:
dataset.shape

(258, 3)

**np.mean()**

Realiza a media dos elementos array ao longo do eixo especificado

In [356]:
# Fazendo a media das colunas axix 0 
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [357]:
# Fazendo a media das linhas axix 1
np.mean(dataset, axis = 1)

array([44830.54666667, 37954.98      , 37315.05333333, 42189.35666667,
       40125.03333333, 36745.91      , 19488.06666667, 63972.81333333,
       73974.42333333, 38851.83      , 28836.19666667, 27992.84333333,
       68168.99666667, 18400.79333333, 56984.80666667, 59177.8       ,
       36526.53      , 30190.46333333, 33932.89666667, 39638.76666667,
       69780.79333333, 32194.46666667, 77867.61333333, 76878.21666667,
       41205.07      , 24462.03333333, 34386.25      , 35817.28      ,
       39298.42333333, 72268.23333333, 34289.06666667, 41477.39333333,
       26365.56333333, 33918.13333333, 50905.01      , 54959.84      ,
       17875.19666667, 41766.95666667, 25768.39333333, 34876.18      ,
       54475.06333333, 59333.43      , 29553.44666667, 75040.79666667,
       39881.91      , 22655.23333333, 52057.21666667, 31725.88333333,
       22240.03333333, 69567.49666667, 78571.96333333, 61600.27666667,
       69114.54333333, 58791.90333333, 31242.99666667, 51282.34333333,
      

In [358]:
# Fazendo a media da coluna 1 e pegando todas as linhas 
np.mean(dataset[:, 1])

44499.41472868217

In [359]:
np.mean(dataset[:, 2])

98960.51310077519

**np.std()**

Desvio padrão

In [360]:
np.std(dataset[:, 2])

29754.101150388564

**ndarray.sum()**

Retorna a soma dos elementos arrays ao longo do eixo especificado

In [361]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
# Fazendo a soma da quilometragem pegando todas as linhas
dataset[:, 1].sum()

**np.sum()**


In [362]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [363]:
np.sum(dataset[:, 1], axis = 0)

11480849.0